openapi: 3.0.0
info:
  title: Sensors API
  version: 1.0.0
  description: API för hantering av vattensensorer

paths:
  /:
    get:
      summary: Hämta alla sensorer
      responses:
        '200':
          description: Lyckad förfrågan
        '404':
          description: Ingen data kunde hämtas
    post:
      summary: Skapa en ny sensor
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - locationID
                - batteryStatus
              properties:
                locationID:
                  type: string
                batteryStatus:
                  type: number
                installationDate:
                  type: string
                  format: date
      responses:
        '201':
          description: Sensor tillagd
        '400':
          description: Fel i begäran

  /waterlevels:
    get:
      summary: Hämta vattennivåer för alla sensorer (mockdata)
      responses:
        '200':
          description: Lyckad förfrågan

  /{sensorID}:
    get:
      summary: Hämta en specifik sensor
      parameters:
        - in: path
          name: sensorID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Sensordata hämtad
        '404':
          description: Sensorn kunde inte hittas

    patch:
      summary: Uppdatera en sensor
      parameters:
        - in: path
          name: sensorID
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                mail:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Sensor uppdaterad
        '400':
          description: Ogiltiga fält
        '404':
          description: Sensorn hittades inte

    delete:
      summary: Ta bort en sensor
      parameters:
        - in: path
          name: sensorID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Sensor borttagen
        '404':
          description: Sensorn hittades inte

  /{sensorID}/waterlevels:
    get:
      summary: Hämta vattennivåer för en sensor
      parameters:
        - in: path
          name: sensorID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Vattennivåer hämtade

  /{sensorID}/historicwaterlevels:
    get:
      summary: Hämta historiska vattennivåer för en sensor
      parameters:
        - in: path
          name: sensorID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Historiska vattennivåer hämtade
