openapi: 3.0.0
info:
  title: Användar-API
  version: 1.0.0
  description: API för att hantera användare

paths:
  /api/users:
    get:
      summary: Retrieve a list of users
      description: Get all users from the system
      responses:
        200:
          description: A list of users
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hämtar alla användare
                  users:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          example: "1"
                        userName:
                          type: string
                          example: Thomas
                        mail:
                          type: string
                          example: thomas.kronvoldt@chasacademy.se
                        role:
                          type: string
                          example: admin

    post:
      summary: Create a new user
      description: Add a new user to the system
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userName:
                  type: string
                  example: JohnDoe
                mail:
                  type: string
                  example: john.doe@example.com
                role:
                  type: string
                  example: user
                password:
                  type: string
                  example: password123
      responses:
        201:
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Användare skapad
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                        example: 123e4567-e89b-12d3-a456-426614174000
                      userName:
                        type: string
                        example: JohnDoe
                      mail:
                        type: string
                        example: john.doe@example.com
                      role:
                        type: string
                        example: user

  /api/users/{id}:
    get:
      summary: Retrieve a specific user
      description: Get a single user from the system by their ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The ID of the user to retrieve
      responses:
        200:
          description: A specific user object
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hämtar en användare
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                        example: "1"
                      userName:
                        type: string
                        example: Thomas
                      mail:
                        type: string
                        example: thomas.kronvoldt@chasacademy.se
                      role:
                        type: string
                        example: admin
        404:
          description: User not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Användare kan inte hittas

    patch:
      summary: Update a user's data
      description: Edit user details such as username, email, and password
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The user ID
