import { query } from './db.js';

console.log("PG_URI:", process.env.PG_URI);
async function setup() {
  try {
    await query(`
      CREATE TABLE "roles" (
        "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "name" VARCHAR(30) NOT NULL
      );
    `);

    await query(`
      CREATE TABLE "users" (
        "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "name" VARCHAR(30) NOT NULL,
        "email" VARCHAR(40) UNIQUE NOT NULL,
        "password" VARCHAR NOT NULL,
        "role_id" INTEGER,
        CONSTRAINT "FK_users.role_id"
          FOREIGN KEY ("role_id")
          REFERENCES "roles"("id")
          ON DELETE SET NULL
      );
    `);

    await query(`
      CREATE TABLE "locations" (
        "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "longitude" DOUBLE PRECISION NOT NULL,
        "latitude" DOUBLE PRECISION NOT NULL,
        "address" VARCHAR(35) NOT NULL,
        "country" VARCHAR(35) NOT NULL
      );
    `);

    await query(`
      CREATE TABLE "sensors" (
        "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "installation_date" TIMESTAMPTZ,
        "battery_status" INTEGER,
        "bitflag" INTEGER,
        "location_id" INTEGER,
        CONSTRAINT "FK_sensors.location_id"
          FOREIGN KEY ("location_id")
          REFERENCES "locations"("id")
          ON DELETE SET NULL
      );
    `);

    await query(`
      CREATE TABLE "waterlevels" (
        "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "waterlevel" INTEGER NOT NULL,
        "mesured_at" TIMESTAMPTZ NOT NULL,
        "sensor_id" INTEGER NOT NULL,
        CONSTRAINT "FK_waterlevels.sensor_id"
          FOREIGN KEY ("sensor_id")
          REFERENCES "sensors"("id")
          ON DELETE CASCADE
      );
    `);

    await query(`
      CREATE TABLE "emergency_contacts" (
        "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "name" VARCHAR(30) NOT NULL,
        "phone_number" VARCHAR(13) NOT NULL,
        "location_id" INTEGER,
        CONSTRAINT "FK_emergency_contacts.location_id"
          FOREIGN KEY ("location_id")
          REFERENCES "locations"("id")
          ON DELETE SET NULL
      );
    `);

    // Optional: Create useful indexes
    await query(`CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);`);
    await query(`CREATE INDEX IF NOT EXISTS idx_sensors_location_id ON sensors(location_id);`);
    await query(`CREATE INDEX IF NOT EXISTS idx_waterlevels_sensor_id ON waterlevels(sensor_id);`);

    console.log("Databasen skapades utan fel.");

  } catch (err) {
    console.error('Fel vid skapande av databas: ', err);
  }
}

setup();
