/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../components/flood-risk-modal/RiskHeader`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/../components/flood-risk-modal/DetailSection`; params?: Router.UnknownInputParams; } | { pathname: `/../components/flood-risk-modal/RiskGauge`; params?: Router.UnknownInputParams; } | { pathname: `/../components/flood-risk-modal/DetailItem`; params?: Router.UnknownInputParams; } | { pathname: `/../constants/mapStyles`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/../components/flood-risk-modal/RiskHeader`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/flood-risk-modal/DetailSection`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/flood-risk-modal/RiskGauge`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/flood-risk-modal/DetailItem`; params?: Router.UnknownOutputParams; } | { pathname: `/../constants/mapStyles`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/../components/flood-risk-modal/RiskHeader${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `/../components/flood-risk-modal/DetailSection${`?${string}` | `#${string}` | ''}` | `/../components/flood-risk-modal/RiskGauge${`?${string}` | `#${string}` | ''}` | `/../components/flood-risk-modal/DetailItem${`?${string}` | `#${string}` | ''}` | `/../constants/mapStyles${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../components/flood-risk-modal/RiskHeader`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/../components/flood-risk-modal/DetailSection`; params?: Router.UnknownInputParams; } | { pathname: `/../components/flood-risk-modal/RiskGauge`; params?: Router.UnknownInputParams; } | { pathname: `/../components/flood-risk-modal/DetailItem`; params?: Router.UnknownInputParams; } | { pathname: `/../constants/mapStyles`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; };
    }
  }
}
